version: '3.7'
networks:
  digicert-bridge:
    driver: bridge
services:
  agencybookingapp:
    build:
      dockerfile: Dockerfile
    image: agencybookingapp
    environment:
      - HOST=192.168.1.31
    volumes:
      - ./log:/opt/deployment/log

    ports:
      - 8080:8080
    networks:
      digicert-bridge:
        aliases:
          - agencybookingapp    

